// Framer Motion presets — generated by designlang (motionlang)
// Source: https://stripe.com
// 2026-05-21T16:43:53.596Z
//
//   import { transitions, variants } from './stripe.com-motion.framer';
//   <motion.div variants={variants.slideUp} initial="hidden" animate="show"
//               transition={transitions.base} />

/** Easing curves extracted from the live page, as Framer cubic-bezier arrays. */
export const easings = {
  easeOut: [0.25, 1, 0.5, 1], // 475× on page
  linear: [0, 0, 1, 1], // 46× on page
  custom4: [0.65, 0, 0.35, 1], // 31× on page
  custom6: [0.3, 0, 0.2, 1], // 16× on page
  custom7: [0.45, 0.05, 0.55, 0.95], // 14× on page
  custom9: [0.6, 0, 0.2, 0.5], // 8× on page
  custom10: [0.4, 0, 0.2, 1], // 7× on page
  easeInOut: [0.25, 0.1, 0.25, 1], // 6× on page
};

/** Duration presets (seconds), extracted from the live page. */
export const durations = {
  xs: 0.1,
  sm: 0.2,
  md: 0.3,
  lg: 0.5,
  xl: 0.8,
};

/** Ready-to-spread Framer Motion transition objects. */
export const transitions = {
  base:  { duration: 0.3, ease: easings.easeOut },
  fast:  { duration: 0.150, ease: easings.easeOut },
  slow:  { duration: 0.540, ease: easings.easeOut },
  spring: { type: 'spring', stiffness: 320, damping: 30 },
};

/** Common variants wired to the extracted timing. */
export const variants = {
  fade: {
    hidden: { opacity: 0 },
    show:   { opacity: 1, transition: transitions.base },
  },
  slideUp: {
    hidden: { opacity: 0, y: 16 },
    show:   { opacity: 1, y: 0, transition: transitions.base },
  },
  scaleIn: {
    hidden: { opacity: 0, scale: 0.96 },
    show:   { opacity: 1, scale: 1, transition: transitions.base },
  },
  stagger: {
    hidden: {},
    show:   { transition: { staggerChildren: 0.075 } },
  },
};

export default { easings, durations, transitions, variants };
