// Auto-generated by designlang. Do not edit by hand.
// Re-extract with `npx designlang <url>` to refresh.
//
// Import next to your token JSON to get type-safe access:
//
//   import type { ColorToken, SpacingToken } from './<host>-tokens';
//   import tokens from './<host>-design-tokens.json';
//
// Source: https://stripe.com
// Generated: 2026-05-21T16:43:53.586Z

export type Hex = `#${string}`;
export type Px  = `${number}px`;
export type Ms  = `${number}ms`;

export type ColorRole = 'primary' | 'secondary' | 'accent';
export type ColorHex  = '#000000' | '#061b31' | '#533afd' | '#50617a' | '#ffffff' | '#64748d' | '#e5edf5' | '#0000ee' | '#1a2c44' | '#2874ad' | '#ff6118' | '#7f7dfc' | '#3c4f69' | '#273951' | '#7389ff' | '#15be53' | '#b9b9f9' | '#a51d85' | '#ffd7ef' | '#5b6bff' | '#00b261' | '#4f2055' | '#7d8ba4' | '#108c3d' | '#d6d9fc' | '#101010' | '#6b59fe' | '#839bc8' | '#a3b5d6' | '#ffe5da' | '#ebeef1' | '#122054' | '#15286a' | '#92adff' | '#81b81a' | '#000eff' | '#d8dee4' | '#ffe6f5' | '#ffa956' | '#2863b1' | '#101d4e' | '#2d2564' | '#00d66f' | '#707070' | '#2b91df' | '#ff4fd5' | '#2b408a' | '#d4d4d4' | '#5d0252' | '#4834db' | '#23356e' | '#171055';
export type ColorToken = ColorRole | ColorHex;

export type FontFamilyToken = 'sohne-var' | 'SourceCodePro';
export type FontSizeToken   = never;
export type FontWeightToken = '400' | '300' | '500' | '700';

export type SpacingToken = '1px' | '48px' | '52px' | '56px' | '60px' | '64px' | '72px' | '80px' | '96px' | '191px' | '244px' | '340px';

export type RadiusToken = '1px' | '4px' | '8px' | '16px' | '28px' | '36px' | '100px';

export type DurationToken = '100ms' | '200ms' | '300ms' | '500ms' | '800ms';
export type EasingToken   = never;

export type MaterialLanguage = 'skeuomorphic';

export interface DesignTokens {
  color: { [role in ColorRole]: ColorHex };
  typography: {
    family: FontFamilyToken;
    size: FontSizeToken;
    weight: FontWeightToken;
  };
  spacing: ReadonlyArray<SpacingToken>;
  radius:  ReadonlyArray<RadiusToken>;
  motion: {
    duration: ReadonlyArray<DurationToken>;
    easing:   ReadonlyArray<EasingToken>;
  };
}

declare const tokens: DesignTokens;
export default tokens;
